@host = localhost
@port = 3000
@uri = http://{{host}}:{{port}}
@contentType = application/json

@thing = person:uv1o55sjes0tdpa3oool

### getHello
// @name getHello

GET {{uri}}
Content-Type: application/json

### postCreate
// @name postCreate
// creates anything

POST {{uri}}/person
Content-Type: application/json

{
  "identifier": "00001",
  "title": "Founder & CEO",
  "name": {
    "first": "Tobie",
    "last": "Morgan Hitchcock"
  },
  "marketing": true
}

### getSelect
// @name getSelect

GET {{uri}}/{{thing}}
Content-Type: application/json

### patchChange
// @name patchChange
// patches anything

PATCH {{uri}}/{{thing}}
Content-Type: application/json

{
  "name": {
    "first": "Mário CHANGED",
    "last": "Monteiro"
  },
  "age": 14
}

### deleteDelete
// @name deleteDelete

DELETE {{uri}}/{{thing}}
Content-Type: application/json

### model

### postCreateModel
// @name postCreateModel

POST {{uri}}/person
Content-Type: application/json

{
  "id": "00001",
  "title": "Founder & CEO",
  "name": {
    "first": "Tobie",
    "last": "Morgan Hitchcock"
  },
  "marketing": true,
  "age": 28,
  "metaData": { "data": "tobie" },
  "metaDataInternal": { "data": "tobie internal" }
}

### getSelectModel
// @name getSelectModel

GET {{uri}}/person/{{thing}}
Content-Type: application/json
